version: '3.3'
services:
  drupal:
    image: drupal:latest
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./data/dump:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
          - db
      environment:
          PMA_ARBITRARY: 1
          MYSQL_USER: "mysql"
          MYSQL_PASSWORD: "mysql"
          MYSQL_ROOT_PASSWORD: "mysql"
      ports:
          - "81:80"
